version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: chatbotbar-n8n
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin@flybots.agency
      - N8N_BASIC_AUTH_PASSWORD=adminpass123
      - N8N_HOST=0.0.0.0
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=true
      - WEBHOOK_URL=https://n8n.denios.flybots.agency
      - TZ=Europe/Madrid
    volumes:
      - ./n8n_data:/home/node/.n8n
    expose:
      - "5678"

  nginx:
    image: nginx:alpine
    container_name: chatbotbar-nginx
    restart: unless-stopped
    depends_on:
      - n8n
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: chatbotbar-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done"
